### ISSUE TITLE
返回的数量

### ISSUE THREAD

**Issue by TaroSunn** [Li-Jiajie/BatchAttachmentDownloader#5]
大佬，设置了时间范围，返回的是最新的23条
2021-01-01 00:00 2022-02-10 18:00
邮件总数: 23

**Comment by Li-Jiajie** [comment]
是这里的邮件总数少于实际吗？
有些邮箱设置了最大拉取数量，需要在邮箱处设定，例如QQ邮箱：
![image](https://user-images.githubusercontent.com/35255760/153411395-fc8896b8-44ba-44b3-bfcf-510cf5b80834.png)

**Comment by TaroSunn** [comment]
> 是这里的邮箱设置了最大的邮箱吗？ ![图片](https://user-images.githubusercontent.com/35255760/153411395-fc8896b8-44ba-44b3-bfcf-510cf5b80834.png)

还真是 尴尬了 感谢大佬！
