### ISSUE TITLE
我新增了一些有趣的功能代码，具体请见详情和Commits

### ISSUE THREAD

**Issue by RuixiangS** [Li-Jiajie/BatchAttachmentDownloader#6]
# 新功能
1. 新增：添加一种保存类DateSubjectClassifySaver，每个主题文件夹加上收件日期前缀
2. 新增：emailinfo.py添加收件人和收件地址属性和对应的筛选器，并在download.py使用
3. 杂务：MAXLINE属性建议设置翻倍值65536，会更加稳定不容易报错
4. 杂务：在main.py中添加基础说明，downloader补充收件人信息传递
5. 补充：收件人和收件地址在download.py设置策略是二选一，暂不能同时使用
期待您的merge

**Comment by Li-Jiajie** [comment]
感谢完善😊
